spring:
  jpa:
    properties:
      hibernate:
        format_sql: true

  data:
    rest:
      base-path: /api


  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password


#security:
#  basic:
#    enabled: false    # Spring security login page
#
#  csrf:
#    disabled: true # Spring security csrf
#
